    program lmppdb
	 implicit none
	 integer i,j,k,l
	 integer totstep,frequency,totframe,totatom,totline
	 integer,allocatable::idtype(:,:,:),frame(:)
	 real(kind=8),allocatable::coord(:,:,:),lx(:,:),ly(:,:),lz(:,:)
	 real(kind=8) a,b,c,dx,dy,dz
	 real(kind=8),parameter::a1=90.0,a2=90.0,a3=90.0
	 character*20 dumpname,atomname,framename,ctemp
	 
	 open(unit=10,file="inp.inp",status="old")
	 read(10,*)totstep
	 read(10,*)frequency
	 read(10,*)totatom
	 read(10,*)dumpname
	 read(10,*)framename
	 read(10,*)totline
	 close(10)
	 
	 totframe=int(totstep/frequency)
	 
! allocate array
     allocate(coord(totframe,totatom,3))
	 allocate(idtype(totframe,totatom,2))
	 allocate(frame(totline))
	 allocate(lx(totframe,2))
	 allocate(ly(totframe,2))
	 allocate(lz(totframe,2))
	 
! read frame file
     open(unit=11,file=framename,status="old")
     do i=1,totline
	    read(11,*)frame(i)
	 end do
	 close(11)
! read dump file
  
     open(unit=12,file=dumpname,status="old")
     do i=1,totframe
	 
! ignore some lines
        do j=1,5
	        read(12,*)
		end do
		
! get box size information

		read(12,*)lx(i,:)
		read(12,*)ly(i,:)
		read(12,*)lz(i,:)
		
		read(12,*)
		
! read atom position

		do j=1,totatom
		    read(12,*)idtype(i,j,:),coord(i,j,:)
		end do
	end do
	
! deal PBC

    do i=1,totframe-1
	
! box size
        a=lx(i,2)-lx(i,1)
		b=ly(i,2)-ly(i,1)
		c=lz(i,2)-lz(i,1)
		
	    do j=1,totatom
! x		
			if(abs(coord(i,j,1)-coord(i+1,j,1)).ge.(a/2.0))then
			    if(coord(i,j,1).gt.coord(i+1,j,1))then
				    coord(i+1,j,1)=coord(i+1,j,1)+a
				else if(coord(i,j,1).lt.coord(i+1,j,1))then
				    coord(i+1,j,1)=coord(i+1,j,1)-a
				end if
			end if
			
! y
            if(abs(coord(i,j,2)-coord(i+1,j,2)).ge.(b/2.0))then
			    if(coord(i,j,2).gt.coord(i+1,j,2))then
				    coord(i+1,j,2)=coord(i+1,j,2)+b
				else if(coord(i,j,2).lt.coord(i+1,j,2))then
				    coord(i+1,j,2)=coord(i+1,j,2)-b
				end if
			end if
			
! z

            if(abs(coord(i,j,3)-coord(i+1,j,3)).ge.(c/2.0))then
			    if(coord(i,j,3).gt.coord(i+1,j,3))then
				    coord(i+1,j,3)=coord(i+1,j,3)+c
				else if(coord(i,j,3).lt.coord(i+1,j,3))then
				    coord(i+1,j,3)=coord(i+1,j,3)-c
				end if
			end if
		end do
	end do
		
! write pdb file
! http://blog.163.com/jey_df/blog/static/182550161201011241110976/

    do i=1,totline
	    write(ctemp,"(I5)")frame(i)
		open(unit=13,file="frame"//trim(adjustl(ctemp))//".pdb",status="new")
		
		write(13,'(A)')'REMARK generated by lmppdb program'
	    write(13,'(A30,I10)')'REMARK The corresponding frame',frame(i)
	    write(13,1001)'CRYST1',a,b,c,a1,a2,a3
		frame(i)=frame(i)/frequency
		
		do j=1,totatom
		    do k=1,totatom
			    if(idtype(frame(i),k,1).eq.j)then
! atom name
				if(idtype(frame(i),k,2).eq.1)then
				    atomname="O"
				end if
				if(idtype(frame(i),k,2).eq.2)then
				    atomname="C"
				end if
				if(idtype(frame(i),k,2).eq.3)then
				    atomname="H"
				end if
				
		        write(13,1002)"ATOM  ",j,atomname,"CHO","A",1,coord(frame(i),k,:)*10.0
				end if
			end do
		end do
		write(13,'(A3)')'TER'
		write(13,'(A3)')'END'
		close(13)
	end do

1001 format(A6,6f8.3)
1002 format(A6,I5,1X,A5,A3,1X,A1,I4,4X,3F8.3)

    end program lmppdb
		